### ISSUE TITLE
MD formatting issues in sections 2.4.11, 2.5, 2.6

### ISSUE THREAD

**Issue by creighton** [adlnet/xAPI-Spec#1033] opened 2017-03-22 14:08 UTC
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#attachments

The markdown seems messed up in the sections around the Attachments section

**Comment by garemoko** [comment] 2017-03-22 15:34
These seem to be caused by self closing anchor tags with no closing </a>
![image](https://cloud.githubusercontent.com/assets/1363163/24205301/e574bafe-0f12-11e7-9c04-8bdf85329746.png)

There's another instance in the statement immutability section and other documents are affected too (e.g. the main title of part 3). 

[We did address this before](https://github.com/adlnet/xAPI-Spec/pull/790) but it looks like the extra links for the test suite broke new things. Looking back over historical versions, it looks like this was broken for a while. I wonder if github updated something in their html version or something to make these tags invalid. 

It does look quite bad; I don't really want to wait for the next release to fix this in master.

**Comment by garemoko** [comment] 2017-03-22 15:38
Yeh, here's a google cache version of the page from march 16th: http://webcache.googleusercontent.com/search?q=cache:https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md

All looks good. I can't see what's different, but clearly Github changed something that's causing this bad html to be an issue.

**Comment by garemoko** [comment] 2017-03-22 18:34
There's the problem:
https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

https://githubengineering.com/a-formal-spec-for-github-markdown/

**Closed** 2017-04-18 12:06 UTC
