### ISSUE TITLE
When PUTing a statement, MUST the statement object have an id? Yes. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#494] opened 2014-09-04 16:47 UTC
For context see: https://github.com/LearningLocker/learninglocker/issues/346

Looking at the current spec, I can see no requirement for a statement to have an id within the statement object itself when it is PUT. There has to be a statementId parameter in the PUT request, but not (explicitly) in the statement. 

At the same time ```` Ids MUST be generated by the LRS if a Statement is received without an id. ```` so it's clear that the LRS MUST NOT use the statement id passed with the PUT for the statement, but must generate a new one, which is nonsensical. 

On that basis, I think we can say it's implied that the activity provider MUST include a statement id within the statement object when making a PUT request. 

This implication is also supported by https://github.com/garemoko/xAPI-Spec/blob/master/xAPI.md#721-putstatements which describes the ````statementId```` as ````Id of Statement to record````. This assumes that the statement has an id. We also say in a description ````POST must be used rather than PUT to save multiple Statements, or to save one Statement without first generating a Statement id```` (you could argue that the requirement to generate a statement id doesn't require you to including it in the statement, but clearly that's not what's intended). 

So we should amend ````Ids SHOULD be generated by the Activity Provider.```` to 
````Ids MUST be generated by the Activity Provider when using PUT requests.````
````Ids SHOULD be generated by the Activity Provider when using POST requests.```

This is a patch.

**Comment by andyjohnson** [comment] 2015-01-20 21:52
We have an interesting problem here.  I think the original requirement of a Statement property id is valid in that we don't need to dump the requirement of generating a GUID on anyone creating Statements (imho).  Unfortunately, some service down the line needs to pick up the slack if the designer does not, whether that be an AP (in the sense of a trusted system of the LRS) or the LRS itself.  The language needs to change somewhere because one requirement dictates the LRS picks up the slack if no one else does, but the other indicates the requester (AP or otherwise) can't submit a PUT without a Statement ID.  

Since this requirement doesn't exist for POST, I motion that we remove it from PUT, as the type of request shouldn't dictate the owner of responsibility.  In other words, just because someone batches their Statements, they shouldn't be any more or less responsible about IDs than if they submitted single PUTs. I'm seeing the paradigm as PUT = single vs. POST = multiple.  If we'd rather that paradigm be PUT = use ids vs. POST = don't use ids, I'm fine with that too, but we need to establish something clearer.

**Comment by fugu13** [comment] 2015-01-20 22:01
PUT must be idempotent and address the resource directly (not the collection the resource will be part of) in RESTful designs (it's a very strong requirement), and those're only possible if the ID is specified. Generally speaking it will always be better if APs generate IDs (be they using PUT or POST) as idempotency is a very important property for preventing duplication, but it makes sense to have a convenience option for the LRS to generate IDs.

**Comment by andyjohnson** [comment] 2015-01-21 14:23
I agree with what is allowed and recommended from a functionality standpoint.  What I am seeing is with the current requirements, we have two places the ID could be pulled from, the Statement itself and from the parameter of the PUT request.  We actually don't define which gets priority should both happen.  Having the id as a parameter in a PUT request and not allowing the typical usage of PUT (updating) seems like an unnecessary and even potentially distracting requirement.

I'll throw this out there as a solution and we can see where/if it falls short: 

1)  APs SHOULD generate IDs (in the Statement) if they plan on using PUT
2)  APs MAY/SHOULD generate IDs (in the Statement) if the plan on using POST
3)  An LRS MUST accept the PUT request parameter ID if there is not one present in the Statement, otherwise the Statement ID SHOULD* be used
4)  It is not recommended a PUT request use a parameter ID as it is better for Statements to have internal IDs if the AP generates it.

**Comment by garemoko** [comment] 2015-01-21 14:40
1-2 look good, but not 3 or 4. Currently the statementId is a required property for PUT and the LRS has to respond with certain error codes based on that parameter. The advantage of this over the id in the statement is that the LRS can process this id quickly without digging into the content of the request. 

IMHO: For PUT Statements, the AP MUST include the statement id as a parameter and SHOULD* include the id as a property within the statement; if they do include it, it MUST match. The LRS MUST always (for PUT statements) use the id provided in the parameter. 

(Note; that's not suggested wording).

**Comment by ryansmith94** [comment] 2015-01-21 15:06
I feel like we're valuing convenience over complexity. Nothing wrong with
that, but these conveniences do not add value, they add more words to a
growing spec.

*When I say conveniences, I mean we're adding multiple ways of doing the
same thing. *

**Comment by ryansmith94** [comment] 2015-01-21 15:15
Removing PUT as suggested in #514 removes this issue.

**Comment by garemoko** [comment] 2015-01-21 15:18
"Removing PUT as suggested in #514 removes this issue."

Yep, but given the order these issues would be tackled in (major vs. patch) this is still worth looking at.

**Comment by ryansmith94** [comment] 2015-01-21 15:22
True. However, if this is added to improve convenience then the issue is the same, you unnecessarily create two ways to do the same thing adding no value.

**Comment by garemoko** [comment] 2015-01-21 15:52
The statement id property and statementId parameter are already there. This issue is around adding clarity to features that already exist to resolve ambiguity.

**Comment by ryansmith94** [comment] 2015-01-21 16:04
I thought this was about removing the need the to send an ID in a PUT request, so I think I may have misread parts, my bad.

**Comment by garemoko** [comment] 2015-01-21 16:20
It may have morphed into that. IMHO that should be a separate issue if it's something we want to do.

**Comment by ryansmith94** [comment] 2015-01-21 16:25
Yeah I agree. I hope we don't want to though.

**Comment by andyjohnson** [comment] 2015-01-21 19:53
Per the 1/21/15 call, 

APs SHOULD provide their own Statement IDs
POST SHOULD be preferred to PUT
If PUT is used, it MUST have an id parameter
If PUT is used, a check MUST be done between the PUT id parameter and the Statement ID (if used), reject if not the same
If PUT is used and no Statement ID can be found, the LRS will populate the Statement with the ID found in the id parameter

**Comment by ryansmith94** [comment] 2015-01-21 19:56
Good stuff @andyjohnson, thanks for the update :+1:

**Comment by garemoko** [comment] 2015-01-21 21:29
So are we deprecating PUT? Should we go as far as to add some descriptive text to that effect?

**Comment by fugu13** [comment] 2015-01-21 21:35
I don't think we can outright deprecate it (that is, no SHOULD*) without a larger conversation, but I think the SHOULD works for now; POST is more versatile

**Closed** 2015-03-02 17:12 UTC
Labels: patch
